name: "Alert Component"

permissions:
  contents: write
  id-token: write
  actions: write

defaults:
  run:
    shell: bash
    working-directory: "packages/components/alert"

on:
  push:
    tags:
      - "@vue-nextui/alert@*"

jobs:
  alert:
    uses: ./.github/workflows/component-publish-npm.yml
    with:
      component: "alert"
