name: Publish the Alert npm package

permissions:
  id-token: write
  contents: read

on:
  push:
    tags:
      - "@vue-nextui/alert@*"

jobs:
  alert:
    uses: ./.github/workflows/publish.yml
    with:
      component: "alert"
