name: Publish the Alert npm package

permissions:
  contents: write
  id-token: write
  actions: write

on:
  push:
    tags:
      - "@vue-nextui/alert@*"

jobs:
  test:
    uses: ./.github/workflows/component-publish-npm.yml
    with:
      component: "alert"
