name: Publish the Button npm package

permissions:
  contents: write
  id-token: write
  actions: write

on:
  push:
    tags:
      - "v*.*.*"
    branches:
      - publish/button
    paths:
      - "packages/components/button/package.json"

jobs:
  test:
    uses: ./.github/workflows/component-publish-npm.yml
    with:
      component: "button"
