name: Publish the Button npm package

permissions:
  contents: write
  id-token: write
  actions: write

on:
  push:
    tags:
      - "@vue-nextui/button@*"

jobs:
  test:
    uses: ./.github/workflows/component-publish-npm.yml
    with:
      component: "button"
