name: "Publish"

on:
  workflow_call:
    inputs:
      component:
        required: true
        type: string

jobs:
  publish:
    defaults:
      run:
        working-directory: "packages/components/${{ inputs.component }}"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: 签出代码
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # - name: 安装 pnpm
      #   uses: pnpm/action-setup@v4

      - name: 设置nodejs
        uses: actions/setup-node@v4
        with:
          # cache: "pnpm"
          node-version: "20"
          registry-url: "https://registry.npmjs.org"

      - name: 安装依赖
        run: npm install

      - name: 运行构建
        run: npm run build

      - name: 发布到npm
        run: "npm publish --no-git-checks"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
