name: "Publish"

permissions:
  contents: write
  id-token: write
  actions: write

on:
  workflow_call:
    inputs:
      component:
        required: true
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    steps:
      - name: 签出代码
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 安装 pnpm
        uses: pnpm/action-setup@v4

      - name: 设置nodejs
        uses: actions/setup-node@v4
        with:
          cache: "pnpm"
          node-version: "20"
          registry-url: "https://registry.npmjs.org"

      - name: 安装依赖
        run: pnpm install
        working-directory: "packages/components/${{ inputs.component }}"

      - name: 运行构建
        run: pnpm run build
        working-directory: "packages/components/${{ inputs.component }}"

      - name: 发布到npm
        run: pnpm publish --no-git-checks --provenance --access=public
        working-directory: "packages/components/${{ inputs.component }}"
