name: Publish Package to npmjs
on:
  push:
    tags:
      - "@vue-nextui/alert@*"
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"
      - run: npm ci
        working-directory: "packages/components/alert"

      - run: npm publish --provenance --access public
        working-directory: "packages/components/alert"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
